language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

script:
  - npm run release
  - cd demo
  - npm i
  - ng lint
  - ng e2e --protractor-config='e2e/protractor.ci.conf.js'
